### ISSUE TITLE
Bug: day-of-week isn't shown based on current locale

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tejpratap46/RecyclerCalendarAndroid#1]
Probably a demo bug, but... :

Should use this, perhaps:

        val dayOfTheWeek = DateFormat.format("EEEEE", calendar.time) as String

Same goes for months names.

**Comment by tejpratap46** [comment]
It's not a bug, you can read day of week any way you want. You can also use any external library it's up to you.

In Demo i used DateFormatSymbols class to get Day Of week and Month name, It is an extensibility feature, You get a Date Object and you can do whatever you want, Convert it to Hebrew Calendar or anything.

**Comment by AndroidDeveloperLB** [comment]
So it's a bug. It doesn't occur on calendar apps.
BTW, Hebrew calendar is very different (based on moon and not the sun). I don't think your library supports it.
I was talking about the name of the days and months, to be written in the current locale.

**Comment by AndroidDeveloperLB** [comment]
Maybe a video should show you why it's a bug. On some cases it shows in Hebrew, and in some, in English. All should be in Hebrew.
In addition, the page-calendar goes in the opposite direction. This is another bug. Perhaps you should update the dependencies

[device-2020-02-25-111918.zip](https://github.com/tejpratap46/RecyclerCalendarAndroid/files/4249111/device-2020-02-25-111918.zip)

**Comment by tejpratap46** [comment]
@AndroidDeveloperLB That video helped a lot, fixed it.

**Comment by AndroidDeveloperLB** [comment]
How did you fix?
Can you please show a new video?

**Comment by tejpratap46** [comment]
Just as you suggested, using `SimpleDateFormat` with given locale

I will attach image of ![Image](https://i.ibb.co/vxMbkjL/use-default-locale.jpg)

**Comment by AndroidDeveloperLB** [comment]
Nice.
