### ISSUE TITLE
Bug: sample of pages doesn't switch between the tabs correctly when in RTL

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [tejpratap46/RecyclerCalendarAndroid#3]
See this:
https://github.com/tejpratap46/RecyclerCalendarAndroid/issues/1#issuecomment-590765621

**Comment by tejpratap46** [comment]
Android View Pager does not support RTL automatically as Pager Tabs does.
We can achieve RTL be reversing View Pager Fragment Order and setting last Fragment as `viewPager.setCurrentItem(lastFragment)` but this demo is not to demonstrate how make View Pager support RTL.

For demo case, just forced Tabs to LTR when RTL is detected.

**Comment by AndroidDeveloperLB** [comment]
That's incorrect. You need to update it to the ViewPager2 , as I remember.
